concurrent = 7
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Test runner"
  url = "http://192.168.1.30:8888"
  id = 6
  token = "2h8y39yDYzx8PdyTxGjc"
  token_obtained_at = 2023-07-27T13:07:46Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "docker"
  url = "http://192.168.1.30:8888"
  id = 8
  token = "sr17_uyvnpHYrnmkP396"
  token_obtained_at = 2023-08-02T19:02:57Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  pre_get_sources_script = "rm -f /builds/*/*/.git/shallow.lock"
  [runners.custom_build_dir]
    enabled = true
  [runners.docker]
    tls_verify = false
    image = "curlimages/curl:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    network_mode = "gitlab_gitlab_minio"
    shm_size = 0

[[runners]]
  name = "docker2"
  url = "http://gitlab.example.com:8888"
  id = 9
  token = "Zbz76aVugNRKptpkwHTh"
  token_obtained_at = 2023-08-03T00:21:59Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  pre_get_sources_script = "rm -f /builds/*/*/.git/shallow.lock"
  [runners.docker]
    tls_verify = false
    image = "curlimages/curl:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    network_mode = "gitlab_gitlab_minio"
    shm_size = 0
