version: '3.7'

## Create network for containers
# GitLab IP: 192.168.1.30
# Minio IP: 192.168.1.10
networks:
  gitlab_minio:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"

## -------------- GitLab --------------------
services:
  gitlab:
    container_name: gitlab_lfs
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8888'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['object_store']['enabled'] = true
        gitlab_rails['object_store']['proxy_download'] = true
        gitlab_rails['object_store']['connection'] = {
          'provider' => 'AWS',
          'region' => 'us-east-1',
          'endpoint' => 'http://192.168.1.10:9000',
          'path_style' => true,
          'aws_access_key_id' => '$MINIO_ROOT_USER',
          'aws_secret_access_key' => '$MINIO_ROOT_PASSWORD'
        }
        gitlab_rails['object_store']['objects']['artifacts']['bucket'] = 'gitlab-artifacts'
        gitlab_rails['object_store']['objects']['external_diffs']['bucket'] = 'gitlab-mr-diffs'
        gitlab_rails['object_store']['objects']['lfs']['bucket'] = 'gitlab-lfs'
        gitlab_rails['object_store']['objects']['uploads']['bucket'] = 'gitlab-uploads'
        gitlab_rails['object_store']['objects']['packages']['bucket'] = 'gitlab-packages'
        gitlab_rails['object_store']['objects']['dependency_proxy']['bucket'] = 'gitlab-dependency-proxy'
        gitlab_rails['object_store']['objects']['terraform_state']['bucket'] = 'gitlab-terraform-state'
        gitlab_rails['object_store']['objects']['ci_secure_files']['bucket'] = 'gitlab-ci-secure-files'
        gitlab_rails['object_store']['objects']['pages']['bucket'] = 'gitlab-pages'
    ports:
      - '8888:8888'
      - '2224:22'
    networks:
      gitlab_minio:
        ipv4_address: 192.168.1.30
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'

## ------------------- MinIO S3 backets --------------------------------------
  minio:
    container_name: minio_stor
    image: 'quay.io/minio/minio'
    restart: always
    hostname: 'minio_stor'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000'
      - '9090:9090'
    networks:
      gitlab_minio:
        ipv4_address: 192.168.1.10
    volumes:
      - '$MINIO_HOME/data:/data'
    command: server /data --console-address ':9090' --address ':9000'

## Service container for creating backets
  createbuckets:
    image: minio/mc
    container_name: createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set lfs-obj http://192.168.1.10:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};

      /usr/bin/mc mb lfs-obj/gitlab-lfs;
      /usr/bin/mc mb lfs-obj/gitlab-artifacts;
      /usr/bin/mc mb lfs-obj/gitlab-mr-diffs;
      /usr/bin/mc mb lfs-obj/gitlab-uploads;
      /usr/bin/mc mb lfs-obj/gitlab-packages;
      /usr/bin/mc mb lfs-obj/gitlab-dependency-proxy;
      /usr/bin/mc mb lfs-obj/gitlab-terraform-state;
      /usr/bin/mc mb lfs-obj/gitlab-ci-secure-files;
      /usr/bin/mc mb lfs-obj/gitlab-pages;

      /usr/bin/mc policy set public lfs-obj/gitlab-lfs;
      /usr/bin/mc policy set public lfs-obj/gitlab-artifacts;
      /usr/bin/mc policy set public lfs-obj/gitlab-mr-diffs;
      /usr/bin/mc policy set public lfs-obj/gitlab-uploads;
      /usr/bin/mc policy set public lfs-obj/gitlab-packages;
      /usr/bin/mc policy set public lfs-obj/gitlab-dependency-proxy;
      /usr/bin/mc policy set public lfs-obj/gitlab-terraform-state;
      /usr/bin/mc policy set public lfs-obj/gitlab-ci-secure-files;
      /usr/bin/mc policy set public lfs-obj/gitlab-pages;

      exit 0;
      "
    networks:
      gitlab_minio:

## --------------------------- GitLab Runner -----------------------------
  gitlab-cicd-runner:
    image: gitlab/gitlab-runner:latest
    container_name:  gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - '/srv/gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      gitlab_minio:
