version: '3.6'
services:
  minio:
    container_name: minio_stor
    image: 'quay.io/minio/minio'
    restart: always
    hostname: 'minio.example.com'
    environment:
      - 'MINIO_ROOT_USER=minio_root'
      - 'MINIO_ROOT_PASSWORD=minio108'
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - '$MINIO_HOME/data:/data'
    command:
      server /data --console-address :9090